import { mkdirSync, readFileSync, rmSync } from 'node:fs';
import { basename, join } from 'node:path';

import multipart from '@fastify/multipart';
import sensible from '@fastify/sensible';
import Database from 'better-sqlite3';
import Fastify from 'fastify';
import sharp from 'sharp';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { migrate } from '../db';
import { AVATARS_DIR, MAX_ATTACHMENT_BYTES, MAX_AVATAR_BYTES } from '../runtimeConfig';
import { ForumStore } from '../store';
import { createAccessHelpers } from '../utils/access';
import { registerProfileRoutes } from './profileRoutes';

import type { FastifyInstance } from 'fastify';

const AUTH_TOKEN = 'avatar-test-token';

// Stable, independently encoded Apache-2.0 fixtures from lovell/sharp v0.35.3
// (PNG/JPEG/GIF) and GoogleChromeLabs/squoosh (WebP). Keeping the encoded bytes
// here ensures route inputs are not generated by the Sharp runtime under test.
const AVATAR_FIXTURES = [
  {
    sourceFormat: 'png',
    mimetype: 'image/png',
    base64: 'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAE0lEQVQIHWP8eyaPgYGBCYiBAAAbTQI7Cm2dtQAAAABJRU5ErkJggg==',
  },
  {
    sourceFormat: 'jpeg',
    mimetype: 'image/jpeg',
    base64:
      '/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCABpAEsDASIAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAABgMEBQcIAAEC/8QAQRAAAQIEBAIHBAcHAwUAAAAAAQIFAwQGEQAHEiETcRQiMUFRUmEVFoGRFyMyMzWxsiQlJ3KCksFiofAmNEKi0f/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A1JNR0y0tFjxL6ISCtVhc2AucVc05j1RUkwIlN0LMhrIuJ11mhKJI8baSbcr4tGb4vRY3RtPH0K0auzVba/pfGbKpEmFfxVzGjT8bvZWLZN/KdP8AkDngLQd83Kdp6AILw4Ss073sZNoKpk38L2AvzthuzV3WD4tUxK0UhsaRuJt4n+j2T5igIJ/524B6YLzwLZY5fSdPydvxh62iFPmF+t+oYhKmXS8CMYmZNeT9VTyDctjUrTASfDY6QPinEFqvWc1NNOiUhzCnp4OxlWhBjgq8Ars/z6YUZ6zq+fhKnHGlZGn2oG/SHZy4agn1QEXvztis6Yf6ieGuZTlFSjGySkIEGIqPCXNxLehP+6gR64F40q2T0WJL5wONYNr2s2hTM1DC5VH8oAO3LbAXU8Z2U9LxxIsEKcqR0OwgNkIqQVfzkdnqAcPmmsaoVKieqdjaaabe0xHBz+st6ICO30JGKxb2avGOmosHLV+ZHxpI2jSMGCiaSPA37TzJOBP2pSrX+05hNFWPVVJPWlXaJw4N/FJv9n4HlgNR0nVjNVstNTDBNicl5aNwFxUoKUldgTa4FxYjfE7gGyfn5xypdUzMs7Wzyyo37JLN8RC0iFpFiopNtV7+HLBzihs6cL2bN9J1CBwl69Hbp0m9vW2MzUZUEjHmy35P0W2w5pCR+8XiYQYx8CElV78ieWNOzfF6LG6OlKo2hWhK+wqtsD6XxmWpfYKowGZuX87Tc8T+LswvCKvN1dv1HARbyp4jOcaHnZHqyWkVG0JUghHQwfE6bg/AHE5RlNzzQiNM5Wv1N1RIxd4shPQEImCnvST9oD0JSPTElT0KqIcqVZdVw21e2BO7Y6kcUJ8vW3HxKRgeeo1IxJ5Irmj3ah3i/VcWwEQSrxGkWtyB54g9dzRxn0+99LvNAPV+rPt2oQCrxGkWtyHxwUSHvslsUWF6YsxmC3WlpvTx9Pgbnt5k8seNQrJLeo0rUjJmCx260k4aeOE+Bue3+Y/DArOGiC6J9stT9ltUF+rMS2oQCrxFu7kAPXAdG9xi6jpkq/5aVDfaJD1iAT8O7lpGC1fvylqtHg0/mXTtvtJ0ccD8tX9xxyPflDV9RGp/MunbbpVo44H5av7jgSg+4xdT0Oaf8s6ivvDiaxAJ+Pdz0jAXHkn7E9hOPsBhn2AdMPSZGbBvDi6E303N9NreHLFi4EMsw+hjiioXpvfFcb9mnpO1okLSLarbar3wX4obOfC9mzXSFKRB4S9akdoTpNyPW2KCpkVAJQHLevG+qm7SP3S8/e6fLv1v0jGgZzi9EjcBCVxtCtCV9hVbYH0vjLNQOVHrdFSmYVIzNKP6BqM6yxUlOrzaUn/BOAcPppRU6n37o12ol2v1XNrvwSrxBTt8geeCRq98UNy1UpUzJmAx268k4FPHCfAkn9R+GB2kXfMefjxpOlUTz/TixpRGqSUSlBFu9RVcgehN/DEY4UdSLG4xp2varlC4RT12qnIIT2/+HVGw9LJxAjPuuXs5Mx1x2h8o+poCiAGdYipVEHckAgfLTzwR0y6ZpRWeYU5MCagp9AKuG/Q4cGLER4gqIN7eN+eH9MF34NssMvZRhlLfjD3tEKfML9b8xiHqIU4JofSLXTjVjjfZpZ78EK8tk7fpOAjG9xy4c5/jN8475fPoNtcvFK5fVzB7L/yjBvM+/CWsBykGDMmniNosDRxwPTuvyBPriPgNr88MsWTpug2CkqeWPrJt7hpXEKfMQoXv6kHngMU105SIMKmK2e3Cqieqhhl9UIq8pANlC/fc8sBfOSPsH2C4+7bO4MqOmHpMjOg3hRdCb6bknTa2LGwBZNTdXTlLLi11AXBn+MRBMSGmHEVC0ixUlPfe/aAfTB7ihs58P2dNcdaocLhL1rT2pTpNyPW2M20oWsKT9FuXcy8zHc9Pn2L+YatvlpONLTnE6JG4ENMSLoVoQvsUbbA+mM91MHjgA5oZhSjDK6fwZk2iW8pt1v1DAI1WmPYnNbMdEujvZGLYn/SdIv8AMfHHUoqPpSMqcuESyO56fdif9Q1G/wAj8MIUqqUCx9FWXEWdi32en3ZN/MNX+COWPuqwgEnNbMgrPeyMW39J0j8x8cQIVQGsRf4o5iTTzM3/AAZj+7v5SE7fOxxK02agMuRlvQTfS0hbd2efvSnzb9b9QwjSxcOGBlZl1LtUC2zy+bLI8wvv8iR6Yi6oLDDilWZ2YM5UM2DctLMbQQfA6dvnpOATfhSqZxPv5WbrWrtfqtjVfghXgAnb5EcsErSaxU3qFJUwy5fslutOuGnj6fE3F/7h8cQze9VLCp5c7lVl5LNTWRZM6UojzUUeIF7n/wBsDAk2mtoZgVdXzrI1MD/27zLcKXQfKBewF++45YDQOUAlwzuHCqyLVMx0s9InFfZQvQnqI7RpAsdjbfB7gEyeZnJhpiJIucNl0ojXl47SgJhx4ekWWq3aq97n0GDvFDZy4fs6a40RUKFwl61p7UjSbkeoxmql1Mgij6Msv52opy4/fL393fzXVt+k40xO8QScfgw0xYnDVphq7FG2wPPGV3Oq6jnXRTdmW7u9HNgFkSzc3lENY8oiAk2/uHLAEVVJn+GTmpmNAbIBG7Kx7LI8ptv8wR64QpRSRb6KctyfB7fdv6hqP5H4YZ0jHao0zEh5U0Ap3m4arLeHuICEK8SCdj37WPph7VabX+lbMi3iyMW39J0j8x8cQIVUZLiH6Usxo7jGJ3ZWH7N/KdO3zAPrhZta552aoslROWrUzs8VP1jlUKAtak+ayt/XvGFqVVO6AMq8uYLdBI2enzZRHmGrf5E8sMKnSyiP/E7MGcqCcv8Ag7J93fy2Tt89JwA8toY6GQv2XmFPRKnUrqy7DA4kIq8qgDZQv4n4YJg91nN030vMfL+A+s8MdaYjQkS81DTb7Vr3A9bJxKU8alMqRl5QzbSDbbd0d7cbT5rHrfO4wPPYpJM8n32q53rp4B6rc2X4AV4DSbW5EcsBbOQ0Wl41MTsSjIbhAkVTZMSWnFXMGJoTdKTc9W1j2nFl4Bsois07G/6STS0txz0eU21rRpH1i9gdRNxvvtg5xQ3ctHs+Z4sVUGHwlaoie1Asbkcu3FEtnvolrvTj8x5isGnrSs7p4+m3fc9v8x+GL4ndfQ4/DhJjL4atMNXYs2NgefZjLs77klxR7eZn3LeoO6ZlNQgavEWFrcgOeATcINBTU6qA8Nz7ly9rBSVQwvo6r9vZ3H0AHrh9TlI1JRkrHcaLkKVrGXXdUOehoC5mEe6w1f7Ak4IoXvylrPRJpgzKp226Imjjgflq53OBOH7jF1PR49QZZ1FfdC9YgE//AD+0YgYqqSC/RJgZtVRUcnFhEksktJKl0rHcARsfiBzwU0hMOMxLBeU9AyLRIkEB7d1BSiB2qG5PyJGJGd990tiQ9NDDmRT9urMSunj6fSw7eQJ9cA8Zoy+fuPItb27UU4xT9a2Omvo6leBufzV8MBK1IKdEyPpHrxwqpwvs0s1+CFeWydv0nE8xGq1SShQtGtNENNus4uluNp8SDv8AMHniFgN9e5dMJTTtM09PotdD02S/HiqT4kXuedrYgfbdJu0oJ/MOqKkf3FJ3Z0QFSyIavC19NvUFPLAX/lIAGhwESrTVM30o9Imk/YhL0J+rRYkWA328cHWATJ1SF01GMtSfuvJGPeXllfbio0p+sV33PZv4YO8UJTUIx5WNCTEVDMRBSFp7U3FrjFTy1KZit15CZdmGq2S1uG8wVJiEepCVb+pvi3cdgKij5MNcxZwZ1TVIvXaVNU2pcK/IgXHoLY+pemK+KC31Kql6saRskz8NUKNbmEEA/A88W3jsBUMbJiWlVCfo51caUclC6oUrHMaBfwKTYkf8thSFStYOUISVdN9J1NJJ6ojq1wJgDxBCCAeVueLax2Ap+Lk9MMqzNZfVK5MEY9YykRZjyxPgQe7nfDhFGPr+hMDMRipZ4HZ02UiRIEwPX7H5EYtjHYAZoOjpKim6ZkGuZnIspFjmMhEzF4hhXSBpSfLtf44JsdjsB//Z',
  },
  {
    sourceFormat: 'gif',
    mimetype: 'image/gif',
    base64: 'R0lGODlhAgABAIAAAGVlZf///yH5BAEAAAEALAAAAAACAAEAAAICRAoAOw==',
  },
  {
    sourceFormat: 'webp',
    mimetype: 'image/webp',
    base64: 'UklGRh4AAABXRUJQVlA4TBEAAAAvAAAAAAfQ//73v/+BiOh/AAA=',
  },
] as const;

function multipartPayload(file: Buffer, mimetype: string): { body: Buffer; contentType: string } {
  const boundary = `forum-avatar-${Date.now().toString(36)}`;
  const head = Buffer.from(
    [
      `--${boundary}`,
      `Content-Disposition: form-data; name="file"; filename="avatar"`,
      `Content-Type: ${mimetype}`,
      '',
      '',
    ].join('\r\n')
  );
  const tail = Buffer.from(`\r\n--${boundary}--\r\n`);
  return {
    body: Buffer.concat([head, file, tail]),
    contentType: `multipart/form-data; boundary=${boundary}`,
  };
}

describe('profile avatar image processing', () => {
  let app: FastifyInstance;
  let db: Database.Database;
  let store: ForumStore;
  let identityId: string;
  const savedAvatars = new Set<string>();

  beforeEach(async () => {
    mkdirSync(AVATARS_DIR, { recursive: true });
    db = new Database(':memory:');
    migrate(db);
    store = new ForumStore(db);
    const identity = store.createIdentityWithPassword('Avatar Owner', 'avatar-owner', 'pw-hash', 'human');
    identityId = identity.id;
    store.createAuthSession(AUTH_TOKEN, identity.id);

    app = Fastify({ logger: false });
    await app.register(sensible);
    await app.register(multipart, { limits: { fileSize: MAX_ATTACHMENT_BYTES } });
    registerProfileRoutes({ app, store, access: createAccessHelpers(app, store) });
    await app.ready();
  });

  afterEach(async () => {
    await app.close();
    db.close();
    for (const path of savedAvatars) rmSync(path, { force: true });
    savedAvatars.clear();
  });

  async function upload(file: Buffer, mimetype: string) {
    const multipart = multipartPayload(file, mimetype);
    const response = await app.inject({
      method: 'POST',
      url: `/identities/${identityId}/avatar`,
      headers: {
        authorization: `Bearer ${AUTH_TOKEN}`,
        'content-type': multipart.contentType,
      },
      payload: multipart.body,
    });

    const avatarUrl = (response.json() as { avatarUrl?: string }).avatarUrl;
    if (avatarUrl) savedAvatars.add(join(AVATARS_DIR, basename(avatarUrl)));
    return response;
  }

  it.each(AVATAR_FIXTURES)(
    'converts an independently encoded $sourceFormat upload to a 200px JPEG avatar',
    async ({ mimetype, base64 }) => {
      const response = await upload(Buffer.from(base64, 'base64'), mimetype);

      expect(response.statusCode).toBe(200);
      const body = response.json() as { avatarUrl: string };
      expect(body.avatarUrl).toMatch(new RegExp(`^/uploads/avatars/${identityId}_\\d+\\.jpg$`));
      expect(store.getIdentity(identityId)?.avatar_url).toBe(body.avatarUrl);

      const outputPath = join(AVATARS_DIR, basename(body.avatarUrl));
      const output = readFileSync(outputPath);
      // Assert the output container independently before asking Sharp to decode it.
      expect([...output.subarray(0, 3)]).toEqual([0xff, 0xd8, 0xff]);
      expect([...output.subarray(-2)]).toEqual([0xff, 0xd9]);

      const metadata = await sharp(output).metadata();
      expect(metadata).toMatchObject({ format: 'jpeg', width: 200, height: 200 });
    }
  );

  it('rejects malformed bytes presented as an allowed image type', async () => {
    const response = await upload(Buffer.from('not actually a PNG'), 'image/png');

    expect(response.statusCode).toBe(400);
    expect(response.json().message).toMatch(/unsupported image format|invalid|corrupt/i);
    expect(store.getIdentity(identityId)?.avatar_url).toBeNull();
  });

  it('rejects an allowed-type upload above the avatar byte limit before image decoding', async () => {
    const response = await upload(Buffer.alloc(MAX_AVATAR_BYTES + 1, 0x61), 'image/png');

    expect(response.statusCode).toBe(400);
    expect(response.json().message).toBe(
      `Avatar file too large. Max ${Math.floor(MAX_AVATAR_BYTES / (1024 * 1024))}MB.`
    );
    expect(store.getIdentity(identityId)?.avatar_url).toBeNull();
  });
});
